// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDf0p1o3_EoBnSE63CwxNjnBZl1Mhb0pg',
    appId: '1:36315976924:web:51e91124acfd06b7485019',
    messagingSenderId: '36315976924',
    projectId: 'flutter-voyagepro',
    authDomain: 'flutter-voyagepro.firebaseapp.com',
    storageBucket: 'flutter-voyagepro.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpIdUWOsbSMqn4mM6lO4bfPCqPs_2N3Xs',
    appId: '1:36315976924:android:d967aed9503c6592485019',
    messagingSenderId: '36315976924',
    projectId: 'flutter-voyagepro',
    storageBucket: 'flutter-voyagepro.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBDf0p1o3_EoBnSE63CwxNjnBZl1Mhb0pg',
    appId: '1:36315976924:web:a220daaf1ce05435485019',
    messagingSenderId: '36315976924',
    projectId: 'flutter-voyagepro',
    authDomain: 'flutter-voyagepro.firebaseapp.com',
    storageBucket: 'flutter-voyagepro.firebasestorage.app',
  );
}
